
ZEROMQ_VER=4.3.5
ZEROMQ_BASE=zeromq-${ZEROMQ_VER}
ZEROMQ_TAR=${ZEROMQ_BASE}.tar.gz

CPPZMQ_VER=4.10.0
CPPZMQ_BASE=cppzmq-${CPPZMQ_VER}
CPPZMQ_TAR=${CPPZMQ_BASE}.tar.gz

MSGPACK_VER=6.1.1
MSGPACK_BASE=msgpack-cxx-${MSGPACK_VER}
MSGPACK_TAR=${MSGPACK_BASE}.tar.gz

YAMLCPP_VER=0.8.0
YAMLCPP_BASE=yaml-cpp-${YAMLCPP_VER}
YAMLCPP_TAR=${YAMLCPP_BASE}.tar.gz

OSCODE=`lsb_release -sc`
TGTDIR=`realpath ${PWD}/libs/target_${OSCODE}`
